### ISSUE TITLE
dsp-linux repository is missing

### ISSUE THREAD

**Issue by toganlabs** [analogdevicesinc/dsp-linux-meta-adi#1]
The SRC_URI for the kernel (linux-adi-src.inc) points to https://github.com/analogdevicesinc/dsp-linux which no longer exists.

**Comment by wintee** [comment]
We are in the process of replacing the current DSP Yocto repositories with some new repositories to resolve some critical problems with the existing repositories.

Dave

**Comment by davidgibsonadi** [comment]
Replacement repositories are now available for the Yocto Linux product.
The required repositories are listed here: https://wiki.analog.com/resources/tools-software/linuxdsp/docs/source-setup
